version: '3.5'
services:
  db:
    container_name: postgres_datawherehouse
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5436:5432"
    networks:
      postgres_learn_net:
        ipv4_address: 10.5.0.5
    
  pgadmin:
    container_name: pgadmin4_datawherehouse
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@admin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5056:80"
    networks:
      postgres_learn_net:
        ipv4_address: 10.5.0.6
    depends_on:
      - db

networks:
  postgres_learn_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
